# Configuration pour Home Assistant - Nabaztag Control
# À ajouter dans configuration.yaml

# Variables d'entrée pour l'adresse IP
input_text:
  nabaztag_ip_address:
    name: "Adresse IP Nabaztag"
    initial: "192.168.0.13"

# Sélecteurs pour les positions et états
input_select:
  nabaztag_ear_position:
    name: "Position des oreilles"
    options:
      - "0"
      - "1"
      - "2"
      - "3"
      - "4"
      - "5"
      - "6"
      - "7"
      - "8"
      - "9"
      - "10"
    initial: "5"

  nabaztag_nose_state:
    name: "État du nez"
    options:
      - "off"
      - "on"
      - "todo"
      - "urgent"
      - "panic"
    initial: "off"

  nabaztag_weather:
    name: "Météo"
    options:
      - "soleil"
      - "nuages"
      - "brouillard"
      - "pluie"
      - "neige"
      - "storm"
    initial: "soleil"

# Scripts pour contrôler le Nabaztag
script:
  nabaztag_move_left_ear:
    alias: "Nabaztag - Oreille gauche"
    sequence:
      - action: shell_command.nabaztag_left_ear
        data:
          position: "{{ states('input_select.nabaztag_ear_position') }}"

  nabaztag_move_right_ear:
    alias: "Nabaztag - Oreille droite"
    sequence:
      - action: shell_command.nabaztag_right_ear
        data:
          position: "{{ states('input_select.nabaztag_ear_position') }}"

  nabaztag_move_both_ears:
    alias: "Nabaztag - Les deux oreilles"
    sequence:
      - action: shell_command.nabaztag_left_ear
        data:
          position: "{{ states('input_select.nabaztag_ear_position') }}"
      - delay: "00:00:01"
      - action: shell_command.nabaztag_right_ear
        data:
          position: "{{ states('input_select.nabaztag_ear_position') }}"

  nabaztag_set_nose:
    alias: "Nabaztag - État du nez"
    sequence:
      - action: shell_command.nabaztag_nose
        data:
          state: >
            {% set nose_state = states('input_select.nabaztag_nose_state') %}
            {% if nose_state == 'off' %}0
            {% elif nose_state == 'on' %}1
            {% elif nose_state == 'todo' %}2
            {% elif nose_state == 'urgent' %}3
            {% elif nose_state == 'panic' %}4
            {% endif %}

  nabaztag_set_weather:
    alias: "Nabaztag - Météo"
    sequence:
      - action: shell_command.nabaztag_weather
        data:
          weather: >
            {% set weather_state = states('input_select.nabaztag_weather') %}
            {% if weather_state == 'soleil' %}0
            {% elif weather_state == 'nuages' %}1
            {% elif weather_state == 'brouillard' %}2
            {% elif weather_state == 'pluie' %}3
            {% elif weather_state == 'neige' %}4
            {% elif weather_state == 'storm' %}5
            {% endif %}

  nabaztag_dance:
    alias: "Nabaztag - Danse des oreilles"
    sequence:
      - repeat:
          count: 3
          sequence:
            - action: shell_command.nabaztag_left_ear
              data:
                position: "0"
            - action: shell_command.nabaztag_right_ear
              data:
                position: "10"
            - delay: "00:00:01"
            - action: shell_command.nabaztag_left_ear
              data:
                position: "10"
            - action: shell_command.nabaztag_right_ear
              data:
                position: "0"
            - delay: "00:00:01"
      - action: shell_command.nabaztag_left_ear
        data:
          position: "5"
      - action: shell_command.nabaztag_right_ear
        data:
          position: "5"

  nabaztag_talk:
    alias: "Nabaztag - Parler"
    fields:
      message:
        description: "Message à faire dire au Nabaztag"
        example: "Bonjour, il est temps de se réveiller"
    sequence:
      - action: shell_command.nabaztag_say
        data:
          text: "{{ message }}"

# Commandes shell
shell_command:
  nabaztag_left_ear: 'curl -s "{{ states("input_text.nabaztag_ip_address") }}/left?p={{ position }}&d=0"'
  nabaztag_right_ear: 'curl -s "{{ states("input_text.nabaztag_ip_address") }}/right?p={{ position }}&d=0"'
  nabaztag_nose: 'curl -s "{{ states("input_text.nabaztag_ip_address") }}/nose?v={{ state }}"'
  nabaztag_weather: 'curl -s "{{ states("input_text.nabaztag_ip_address") }}/weather?v={{ weather }}"'
  
  # Commandes pour la synthèse vocale (testez ces différentes variantes)
  nabaztag_say: 'curl -s "{{ states("input_text.nabaztag_ip_address") }}/tts?text={{ text | urlencode }}"'
  nabaztag_say_alt1: 'curl -s "{{ states("input_text.nabaztag_ip_address") }}/say?text={{ text | urlencode }}"'
  nabaztag_say_alt2: 'curl -s "{{ states("input_text.nabaztag_ip_address") }}/speak?message={{ text | urlencode }}"'
  nabaztag_play_sound: 'curl -s "{{ states("input_text.nabaztag_ip_address") }}/sound?id=1"'

# Automatisations d'exemple
automation:
  - alias: "Nabaztag - Réveil matin"
    trigger:
      - trigger: time
        at: "07:00:00"
    action:
      - action: script.nabaztag_dance
      - action: script.nabaztag_set_nose
        data:
          state: "1"

  - alias: "Nabaztag - Météo automatique"
    trigger:
      - trigger: time
        at: "08:00:00"
    action:
      - action: script.nabaztag_set_weather
        data:
          weather: >
            {% set weather_condition = states('weather.home') %}
            {% if 'sun' in weather_condition %}0
            {% elif 'cloud' in weather_condition %}1
            {% elif 'fog' in weather_condition %}2
            {% elif 'rain' in weather_condition %}3
            {% elif 'snow' in weather_condition %}4
            {% elif 'storm' in weather_condition %}5
            {% else %}0{% endif %}

  - alias: "Nabaztag - Notification urgente"
    trigger:
      - trigger: state
        entity_id: binary_sensor.door_contact
        to: 'on'
    action:
      - action: script.nabaztag_set_nose
        data:
          state: "3"  # urgent
      - repeat:
          count: 5
          sequence:
            - action: shell_command.nabaztag_left_ear
              data:
                position: "0"
            - action: shell_command.nabaztag_right_ear
              data:
                position: "10"
            - delay: "00:00:01"
            - action: shell_command.nabaztag_left_ear
              data:
                position: "10"
            - action: shell_command.nabaztag_right_ear
              data:
                position: "0"
            - delay: "00:00:01"
