# ==========================================
# AUTOMATISATION NABAZTAG VIVANT
# Active de 8h à 17h avec actions aléatoires
# Compatible avec vos rest_command existantes
# ==========================================

# Automatisation principale - Démarrage à 8h
automation:
  - id: nabaztag_start_day
    alias: "Nabaztag - Démarrer la journée"
    trigger:
      - trigger: time
        at: "08:00:00"
    condition:
      - condition: time
        weekday:
          - mon
          - tue
          - wed
          - thu
          - fri
          - sat
          - sun
    action:
      - action: script.nabaztag_wake_up
      - delay: "00:02:00"
      - action: automation.turn_on
        target:
          entity_id: automation.nabaztag_random_actions

  # Automatisation - Arrêt à 17h
  - id: nabaztag_end_day
    alias: "Nabaztag - Terminer la journée"
    trigger:
      - trigger: time
        at: "22:00:00"
    action:
      - action: automation.turn_off
        target:
          entity_id: automation.nabaztag_random_actions
      - action: script.nabaztag_sleep_sequence

  # Automatisation - Actions aléatoires (toutes les 15-45 minutes)
  - id: nabaztag_random_actions
    alias: "Nabaztag - Actions aléatoires"
    trigger:
      - trigger: time_pattern
        minutes: "/15"
    condition:
      - condition: time
        after: "08:00:00"
        before: "17:00:00"
      - condition: template
        value_template: "{{ (range(1,4) | random) == 1 }}" # 33% de chance
    action:
      - action: script.nabaztag_random_action

        # Actions aux heures pleines
  - id: nabaztag_hourly_action
    alias: "Nabaztag - Action horaire"
    trigger:
      - trigger: time_pattern
        minutes: 0
    condition:
      - condition: time
        after: "08:00:00"
        before: "17:00:00"
    action:
      - action: script.nabaztag_announce_time
      - delay: "00:00:05"
      - action: script.nabaztag_random_action

  # Pause déjeuner (12h)
  - id: nabaztag_lunch_break
    alias: "Nabaztag - Pause déjeuner"
    trigger:
      - trigger: time
        at: "12:00:00"
    action:
      - action: rest_command.nabaztag_say
        data:
          message: "C'est%20l'heure%20du%20d%C3%A9jeuner%20!%20Bon%20app%C3%A9tit%20%C3%A0%20tous%20!"
      - action: rest_command.nabaztag_set_nose
        data:
          state: 1
          nose_color: "red"
      - delay: "00:00:03"
      - action: rest_command.nabaztag_set_nose
        data:
          state: 1
          nose_color: "green"

  # Retour de pause déjeuner (13h)
  - id: nabaztag_back_from_lunch
    alias: "Nabaztag - Retour déjeuner"
    trigger:
      - trigger: time
        at: "13:00:00"
    action:
      - action: rest_command.nabaztag_say
        data:
          message: "J'esp%C3%A8re%20que%20vous%20avez%20bien%20mang%C3%A9%20!%20On%20reprend%20!"
      - action: script.nabaztag_stretch
# ==========================================
# SCRIPTS PRINCIPAUX
# ==========================================

script:
  # Réveil du matin
  nabaztag_wake_up:
    alias: "Nabaztag - Réveil"
    sequence:
      - action: rest_command.nabaztag_wakeup
      - delay: "00:00:02"
      - action: rest_command.nabaztag_taichi
        data:
          speed: 500  # Vitesse moyenne
      - delay: "00:00:03"
      - action: rest_command.nabaztag_move_left_ear
        data:
          position: 8
      - action: rest_command.nabaztag_move_right_ear
        data:
          position: 8
      - delay: "00:00:01"
      - action: rest_command.nabaztag_say
        data:
          message: "Bonjour%20!%20Je%20me%20r%C3%A9veille%20pour%20une%20nouvelle%20journ%C3%A9e%20!"
      - action: rest_command.nabaztag_set_nose
        data:
          state: 1
          nose_color: "green"

  # Endormissement du soir
  nabaztag_sleep_sequence:
    alias: "Nabaztag - Dodo"
    sequence:
      - action: rest_command.nabaztag_say
        data:
          message: "Bonne%20soir%C3%A9e%20!%20Je%20vais%20me%20reposer%20maintenant."
      - delay: "00:00:03"
      - action: rest_command.nabaztag_taichi
        data:
          speed: 100  # Vitesse lente
      - delay: "00:00:02"
      - action: rest_command.nabaztag_move_left_ear
        data:
          position: 0
      - action: rest_command.nabaztag_move_right_ear
        data:
          position: 0
      - action: rest_command.nabaztag_set_nose
        data:
          state: 0
          nose_color: "off"
      - delay: "00:00:02"
      - action: rest_command.nabaztag_sleep

  # Action aléatoire
  nabaztag_random_action:
    alias: "Nabaztag - Action aléatoire"
    sequence:
      - variables:
          action_type: "{{ range(1, 8) | random }}"
      - choose:
          - conditions:
              - condition: template
                value_template: "{{ action_type == 1 }}"
            sequence:
              - action: script.nabaztag_tell_joke
          - conditions:
              - condition: template
                value_template: "{{ action_type == 2 }}"
            sequence:
              - action: script.nabaztag_announce_weather
          - conditions:
              - condition: template
                value_template: "{{ action_type == 3 }}"
            sequence:
              - action: script.nabaztag_announce_time
          - conditions:
              - condition: template
                value_template: "{{ action_type == 4 }}"
            sequence:
              - action: script.nabaztag_stretch
          - conditions:
              - condition: template
                value_template: "{{ action_type == 5 }}"
            sequence:
              - action: script.nabaztag_yawn
          - conditions:
              - condition: template
                value_template: "{{ action_type == 6 }}"
            sequence:
              - action: script.nabaztag_ear_dance
          - conditions:
              - condition: template
                value_template: "{{ action_type == 7 }}"
            sequence:
              - action: script.nabaztag_random_sound

  # Dire une blague
  nabaztag_tell_joke:
    alias: "Nabaztag - Raconter une blague"
    sequence:
      - variables:
          joke: >
            {% set jokes = [
              "Pourquoi%20les%20plongeurs%20plongent-ils%20toujours%20en%20arri%C3%A8re%20et%20jamais%20en%20avant%20?%20Parce%20que%20sinon,%20ils%20tombent%20dans%20le%20bateau%20!",
              "Que%20dit%20un%20escargot%20quand%20il%20croise%20une%20limace%20?%20Regarde,%20un%20nudiste%20!",
              "Qu'est-ce%20qui%20est%20jaune%20et%20qui%20attend%20?%20Jonathan%20!",
              "Pourquoi%20les%20poissons%20n'aiment%20pas%20jouer%20au%20tennis%20?%20Parce%20qu'ils%20ont%20peur%20du%20filet%20!",
              "Comment%20appelle-t-on%20un%20chat%20tomb%C3%A9%20dans%20un%20pot%20de%20peinture%20le%20jour%20de%20No%C3%ABl%20?%20Un%20chat-mallow%20!",
              "Que%20dit%20un%20informaticien%20quand%20il%20se%20noie%20?%20F1%20!%20F1%20!",
              "Pourquoi%20les%20dinosaures%20ne%20parlent%20pas%20?%20Parce%20qu'ils%20sont%20morts%20!",
              "Comment%20fait-on%20pour%20allumer%20un%20barbecue%20breton%20?%20On%20utilise%20des%20breizh%20!",
              "Qu'est-ce%20qui%20est%20transparent%20et%20qui%20sent%20la%20carotte%20?%20Un%20pet%20de%20lapin%20!",
              "Pourquoi%20Mickey%20Mouse%20?%20Parce%20que%20Mario%20Bros%20!"
            ] %}
            {{ jokes | random }}
      - action: rest_command.nabaztag_set_nose
        data:
          state: 1
          nose_color: "orange"
      - action: rest_command.nabaztag_communication
      - delay: "00:00:01"
      - action: rest_command.nabaztag_say
        data:
          message: "{{ joke }}"
      - delay: "00:00:02"
      - action: rest_command.nabaztag_set_nose
        data:
          state: 1
          nose_color: "green"

  # Annoncer la météo
  nabaztag_announce_weather:
    alias: "Nabaztag - Annoncer la météo"
    sequence:
      - action: rest_command.nabaztag_set_weather
        data:
          weather: "{{ ['sun', 'clouds', 'rain'] | random }}"
          weather_icon: "{{ ['sun', 'clouds', 'rain'] | random }}"
      - delay: "00:00:02"
      - action: rest_command.nabaztag_say
        data:
          message: >
            {% set weather_messages = [
              "Il%20fait%20beau%20aujourd'hui%20!%20Parfait%20pour%20sortir%20!",
              "Le%20temps%20est%20nuageux%20mais%20agr%C3%A9able%20!",
              "Il%20pleut%20un%20peu,%20n'oubliez%20pas%20votre%20parapluie%20!",
              "Quelle%20belle%20journ%C3%A9e%20pour%20une%20promenade%20!",
              "Le%20ciel%20est%20d%C3%A9gag%C3%A9,%20profitez-en%20bien%20!"
            ] %}
            {{ weather_messages | random }}

  # Annoncer l'heure
  nabaztag_announce_time:
    alias: "Nabaztag - Annoncer l'heure"
    sequence:
      - action: rest_command.nabaztag_ack
      - delay: "00:00:01"
      - action: rest_command.nabaztag_say
        data:
          message: "Il est {{ now().strftime('%H heures %M') }}"

  # Étirement (Taichi)
  nabaztag_stretch:
    alias: "Nabaztag - S'étirer"
    sequence:
      - action: rest_command.nabaztag_say
        data:
          message: "{{ ['Allez,%20un%20petit%20%C3%A9tirement%20!',%20'Time%20de%20se%20d%C3%A9gourdir%20!',%20'Un%20peu%20d%20exercice%20!'] | random }}"
      - delay: "00:00:02"
      - action: rest_command.nabaztag_taichi
        data:
          speed: 1000  # Vitesse maximale
      - delay: "00:00:05"
      - action: rest_command.nabaztag_taichi
        data:
          speed: 500   # Retour vitesse normale

  # Bâillement
  nabaztag_yawn:
    alias: "Nabaztag - Bâiller"
    sequence:
      - action: rest_command.nabaztag_say
        data:
          message: "{{ ['Haaaaa...%20petit%20b%C3%A2illement%20!',%20'Je%20suis%20un%20peu%20fatigu%C3%A9...',%20'Hooooo...%20excusez-moi%20'] | random }}"
      - action: rest_command.nabaztag_move_left_ear
        data:
          position: 0
      - action: rest_command.nabaztag_move_right_ear
        data:
          position: 0
      - delay: "00:00:02"
      - action: rest_command.nabaztag_move_left_ear
        data:
          position: 16
      - action: rest_command.nabaztag_move_right_ear
        data:
          position: 16
      - delay: "00:00:01"
      - action: rest_command.nabaztag_move_left_ear
        data:
          position: 8
      - action: rest_command.nabaztag_move_right_ear
        data:
          position: 8

  # Danse des oreilles
  nabaztag_ear_dance:
    alias: "Nabaztag - Danse des oreilles"
    sequence:
      - action: rest_command.nabaztag_communication
      - repeat:
          count: 5
          sequence:
            - action: rest_command.nabaztag_move_left_ear
              data:
                position: "{{ range(0, 17) | random }}"
            - action: rest_command.nabaztag_move_right_ear
              data:
                position: "{{ range(0, 17) | random }}"
            - delay: "00:00:00.5"
      - action: rest_command.nabaztag_move_left_ear
        data:
          position: 8
      - action: rest_command.nabaztag_move_right_ear
        data:
          position: 8

  # Son aléatoire
  nabaztag_random_sound:
    alias: "Nabaztag - Son aléatoire"
    sequence:
      - variables:
          sound_choice: "{{ range(1, 4) | random }}"
      - choose:
          - conditions:
              - condition: template
                value_template: "{{ sound_choice == 1 }}"
            sequence:
              - action: rest_command.nabaztag_communication
          - conditions:
              - condition: template
                value_template: "{{ sound_choice == 2 }}"
            sequence:
              - action: rest_command.nabaztag_ack
          - conditions:
              - condition: template
                value_template: "{{ sound_choice == 3 }}"
            sequence:
              - action: rest_command.nabaztag_ministop
      - action: rest_command.nabaztag_set_nose
        data:
          state: 1
          nose_color: "{{ ['red', 'orange', 'green'] | random }}"
      - delay: "00:00:02"
      - action: rest_command.nabaztag_set_nose
        data:
          state: 1
          nose_color: "green"

  # Action surprise
  nabaztag_surprise_action:
    alias: "Nabaztag - Surprise"
    sequence:
      - action: script.turn_on
        target:
          entity_id: script.nabaztag_dance
      - action: rest_command.nabaztag_surprise