# ==========================================
# AUTOMATISATION NABAZTAG VIVANT - VERSION CORRIGÉE
# Active de 8h à 17h avec actions aléatoires
# ==========================================
    
# Automatisation principale - Démarrage à 8h
automation:
  - id: nabaztag_start_day
    alias: "Nabaztag - Actions aléatoires ON"
    trigger:
      - trigger: time
        at: "07:05:00"  # 5 min après le réveil existant
    condition:
      - condition: state
        entity_id: input_boolean.nabaztaglife
        state: "on"  # Seulement si déjà réveillé
    action:
      - action: automation.turn_on
        target:
          entity_id: automation.nabaztag_random_actions

  # Automatisation - Arrêt à 21h45 (avant le coucher existant)
  - id: nabaztag_end_day
    alias: "Nabaztag - Actions aléatoires OFF"
    trigger:
      - trigger: time
        at: "21:45:00"
    condition:
      - condition: state
        entity_id: input_boolean.nabaztaglife
        state: "on"
    action:
      - action: automation.turn_off
        target:
          entity_id: automation.nabaztag_random_actions

  # Automatisation - Actions aléatoires (toutes les 15 minutes)
  - id: nabaztag_random_actions
    alias: "Nabaztag - Actions aléatoires"
    trigger:
      - trigger: time_pattern
        minutes: "/15"
    condition:
      - condition: time
        after: "07:00:00"
        before: "21:45:00"
      - condition: state
        entity_id: input_boolean.nabaztaglife
        state: "on"
      - condition: template
        value_template: "{{ (range(1,4) | random) == 1 }}" # 33% de chance
    action:
      - action: script.nabaztag_random_action

  # Actions aux heures pleines
  - id: nabaztag_hourly_action
    alias: "Nabaztag - Action horaire"
    trigger:
      - trigger: time_pattern
        minutes: 0
    condition:
      - condition: time
        after: "07:00:00"
        before: "21:45:00"
      - condition: state
        entity_id: input_boolean.nabaztaglife
        state: "on"
    action:
      - action: script.nabaztag_announce_time
      - delay: "00:00:05"
      - action: script.nabaztag_random_action

  # Pause déjeuner (12h)
  - id: nabaztag_lunch_break
    alias: "Nabaztag - Pause déjeuner"
    trigger:
      - trigger: time
        at: "12:30:00"
    condition:
      - condition: state
        entity_id: input_boolean.nabaztaglife
        state: "on"  # Seulement si le Nabaztag est réveillé
    action:
      - action: rest_command.nabaztag_say
        data:
          message: "ses lheure du daisjeuner ! Bon appaittit a tous !"
      - action: rest_command.nabaztag_nose
        data:
          state: 1
          nose_color: "red"
      - delay: "00:00:03"
      - action: rest_command.nabaztag_nose
        data:
          state: 1
          nose_color: "00FF00"  # Vert en hex

  # Retour de pause déjeuner (13h)
  - id: nabaztag_back_from_lunch
    alias: "Nabaztag - Retour déjeuner"
    trigger:
      - trigger: time
        at: "13:30:00"
    condition:
      - condition: state
        entity_id: input_boolean.nabaztaglife
        state: "on"  # Seulement si le Nabaztag est réveillé
    action:
      - action: rest_command.nabaztag_say
        data:
          message: "Jespaire que vous avez bien manger ! On reprend !"
      - action: script.nabaztag_stretch

  # Cours du Bitcoin (mise à jour toutes les heures pendant la journée)
  - alias: "Nabaztag - Bitcoin Update Auto"
    id: nabaztag_bitcoin_update_auto
    trigger:
      - trigger: time_pattern
        hours: "/1"
    condition:
      - condition: state
        entity_id: input_boolean.nabaztaglife
        state: "on"
      - condition: not
        conditions:
          - condition: state
            entity_id: input_select.nabaztag_stocks
            state: "Off"
      - condition: time
        after: "09:00:00"
        before: "18:00:00"
      - condition: template
        value_template: >
          {% set current = states('sensor.bitcoin_exchange_rate') | float %}
          {% set previous = states('input_number.bitcoin_previous_exchange_rate') | float %}
          {{ (current - previous) | abs > (previous * 0.05) }}
    action:
      - variables:
          current: "{{ states('sensor.bitcoin_exchange_rate') | float }}"
          previous: "{{ states('input_number.bitcoin_previous_exchange_rate') | float }}"
          diff: "{{ current - previous }}"
      - action: input_number.set_value
        target:
          entity_id: input_number.bitcoin_previous_exchange_rate
        data:
          value: "{{ current }}"
      - action: rest_command.nabaztag_stock
        data:
          value: >
            {% if diff > 500 %}
              6
            {% elif diff > 200 %}
              5
            {% elif diff > 50 %}
              4
            {% elif diff > -50 %}
              3
            {% elif diff > -200 %}
              2
            {% elif diff > -500 %}
              1
            {% else %}
              0
            {% endif %}

# ==========================================
# SCRIPTS PRINCIPAUX
# ==========================================

script:
  # Action aléatoire
  nabaztag_random_action:
    alias: "Nabaztag - Action aléatoire"
    sequence:
      - variables:
          action_type: "{{ range(1, 9) | random }}"
      - choose:
          - conditions:
              - condition: template
                value_template: "{{ action_type == 1 }}"
            sequence:
              - action: script.nabaztag_tell_joke
          - conditions:
              - condition: template
                value_template: "{{ action_type == 2 }}"
            sequence:
              - action: script.nabaztag_announce_weather
          - conditions:
              - condition: template
                value_template: "{{ action_type == 3 }}"
            sequence:
              - action: script.nabaztag_announce_time
          - conditions:
              - condition: template
                value_template: "{{ action_type == 4 }}"
            sequence:
              - action: script.nabaztag_stretch
          - conditions:
              - condition: template
                value_template: "{{ action_type == 5 }}"
            sequence:
              - action: script.nabaztag_yawn
          - conditions:
              - condition: template
                value_template: "{{ action_type == 6 }}"
            sequence:
              - action: script.nabaztag_ear_dance
          - conditions:
              - condition: template
                value_template: "{{ action_type == 7 }}"
            sequence:
              - action: script.nabaztag_random_sound
          - conditions:
              - condition: template
                value_template: "{{ action_type == 8 }}"
            sequence:
              - action: script.nabaztag_surprise_action
          - conditions:
              - condition: template
                value_template: "{{ action_type == 9 }}"
            sequence:
              - action: script.nabaztag_bitcoin_info


  # Dire une blague
  nabaztag_tell_joke:
    alias: "Nabaztag - Raconter une blague"
    sequence:
      - action: rest_command.nabaztag_nose
        data:
          state: 1
          nose_color: "FF8000"  # Orange en hex
      - action: rest_command.nabaztag_communication
      - delay: "00:00:01"
      - action: rest_command.nabaztag_say
        data_template:
          message: >
            {% set jokes = [
              "Pourquoi les plongeurs plongent-ils toujours en arriaire et jamais en avant ? Parce que sinon ils tombent dans le bateau !",
              "Que dit un escargot quand il croise une limace ? Regarde un nudiste !",
              "Quest-ce qui est jaune et qui attend ? Jonathan !",
              "Pourquoi les poissons naiment pas jouer au tennis ? Parce quils ont peur du filet !",
              "Comment appelle-t-on un chat tomber dans un pot de peinture le jour de Noel ? Un chat-mallow !",
              "Que dit un informaticien quand il se noie ? F1 F1 !",
              "Comment fait-on pour allumer un barbecue breton ? On utilise des breizh !",
              "Quest-ce qui est transparent et qui sent la carotte ? Un pet de lapin !",
              "Pourquoi Mickey Mouse ? Parce que Mario Bros !"
            ] %}
            {{ jokes | random }}
      - delay: "00:00:02"
      - action: rest_command.nabaztag_nose
        data:
          state: 1
          nose_color: "00FF00"  # Vert en hex

# Annoncer la météo (utilise weather.forecast_maison)
  nabaztag_announce_weather:
    alias: "Nabaztag - Annoncer la météo"
    sequence:
      - variables:
          meteo: "{{ states('weather.forecast_maison') }}"
          temperature: "{{ state_attr('weather.forecast_maison', 'temperature') }}"
      - action: rest_command.nabaztag_weather
        data:
          weather: >
            {% if meteo in ["sunny", "clear"] %}
              0
            {% elif meteo in ["partlycloudy", "cloudy", "overcast"] %}
              1
            {% elif meteo == "fog" %}
              2
            {% elif meteo in ["rainy", "pouring"] %}
              3
            {% elif meteo in ["snowy", "snowy-rainy"] %}
              4
            {% elif meteo in ["lightning", "lightning-rainy"] %}
              5
            {% else %}
              1
            {% endif %}
      - delay: "00:00:02"
      - action: rest_command.nabaztag_say
        data:
          message: >
            {% if meteo in ["sunny", "clear"] %}
              Il fait beau aujourd'hui avec {{ temperature }} degr%C3%A9s !
            {% elif meteo in ["partlycloudy", "cloudy", "overcast"] %}
              Le temps est nuageux avec {{ temperature }} degr%C3%A9s.
            {% elif meteo in ["rainy", "pouring"] %}
              Il pleut, prevoyez un parapluie ! Temperature : {{ temperature }} degr%C3%A9s.
            {% elif meteo in ["snowy", "snowy-rainy"] %}
              Il neige dehors ! Temperature : {{ temperature }} degr%C3%A9s.
            {% elif meteo in ["lightning", "lightning-rainy"] %}
              Il y a de l'orage ! Temperature : {{ temperature }} degr%C3%A9s.
            {% else %}
              La meteo actuelle est {{ meteo }} avec {{ temperature }} degr%C3%A9s.
            {% endif %}

  # Annoncer l'heure
  nabaztag_announce_time:
    alias: "Nabaztag - Annoncer l'heure"
    sequence:
      - action: rest_command.nabaztag_ack
      - delay: "00:00:01"
      - action: rest_command.nabaztag_say
        data_template:
          message: "Il est {{ now().strftime('%H heures %M') }}"

  # Étirement (Taichi)
  nabaztag_stretch:
    alias: "Nabaztag - S'étirer"
    sequence:
      - action: rest_command.nabaztag_say
        data_template:
          message: "{{ ['Allez un petit %C3%A9tirement !', 'Il est temps de se d%C3%A9gourdir !', 'Un peu dexercice !'] | random }}"
      - delay: "00:00:05"
      - action: rest_command.nabaztag_taichi
        data:
          level: 255
      - delay: "00:00:02"
      - action: rest_command.nabaztag_taichi
        data:
          level: 1000

  # Bâillement
  nabaztag_yawn:
    alias: "Nabaztag - Bâiller"
    sequence:
      - action: rest_command.nabaztag_say
        data_template:
          message: "{{ ['Haaaaa petit baillement !', 'Je suis un peu fatiguer', 'Hooooo excusez-moi'] | random }}"
      - action: rest_command.nabaztag_left_ear
        data:
          position: 0
      - action: rest_command.nabaztag_right_ear
        data:
          position: 0
      - delay: "00:00:02"
      - action: rest_command.nabaztag_left_ear
        data:
          position: 16
      - action: rest_command.nabaztag_right_ear
        data:
          position: 16
      - delay: "00:00:01"
      - action: rest_command.nabaztag_left_ear
        data:
          position: 8
      - action: rest_command.nabaztag_right_ear
        data:
          position: 8

  # Danse des oreilles (compatible avec script existant)
  nabaztag_ear_dance:
    alias: "Nabaztag - Danse des oreilles"
    sequence:
      - action: rest_command.nabaztag_communication
      - repeat:
          count: 3
          sequence:
            - action: rest_command.nabaztag_left_ear
              data:
                position: "{{ range(0, 11) | random }}"
            - action: rest_command.nabaztag_right_ear
              data:
                position: "{{ range(0, 11) | random }}"
            - delay: "00:00:00.5"
            - action: rest_command.nabaztag_nose
              data:
                state: 1
                nose_color: "{{ ['FF0000', '00FF00', '0000FF', 'FFFF00', 'FF00FF', 'FF8000'] | random }}"
            - delay: "00:00:00.5"
      - action: rest_command.nabaztag_left_ear
        data:
          position: 8
      - action: rest_command.nabaztag_right_ear
        data:
          position: 8

  # Son aléatoire
  nabaztag_random_sound:
    alias: "Nabaztag - Son aléatoire"
    sequence:
      - variables:
          sound_choice: "{{ range(1, 4) | random }}"
      - choose:
          - conditions:
              - condition: template
                value_template: "{{ sound_choice == 1 }}"
            sequence:
              - action: rest_command.nabaztag_communication
          - conditions:
              - condition: template
                value_template: "{{ sound_choice == 2 }}"
            sequence:
              - action: rest_command.nabaztag_ack
          - conditions:
              - condition: template
                value_template: "{{ sound_choice == 3 }}"
            sequence:
              - action: rest_command.nabaztag_ministop
      - action: rest_command.nabaztag_nose
        data:
          state: 1
          nose_color: "{{ ['FF0000', 'FF8000', '00FF00'] | random }}"
      - delay: "00:00:02"
      - action: rest_command.nabaztag_nose
        data:
          state: 1
          nose_color: "00FF00"  # Vert en hex

  # Script de danse (utilise le script existant)
  nabaztag_dance:
    alias: "Nabaztag - Danse"
    sequence:
      - action: rest_command.nabaztag_taichi
        data:
          level: 1000
      - delay: "00:00:02"
      - repeat:
          count: 3
          sequence:
            - action: rest_command.nabaztag_left_ear
              data:
                position: "{{ range(0, 11) | random }}"
            - action: rest_command.nabaztag_right_ear
              data:
                position: "{{ range(0, 11) | random }}"
            - delay: "00:00:00.5"
            - action: rest_command.nabaztag_nose
              data:
                state: 1
                nose_color: "{{ ['FF0000', '00FF00', '0000FF', 'FFFF00', 'FF00FF', 'FF8000'] | random }}"
            - delay: "00:00:00.5"
      - action: rest_command.nabaztag_nose
        data:
          state: 1
          nose_color: "8000FF"  # Purple en hex

  # Action surprise
  nabaztag_surprise_action:
    alias: "Nabaztag - Surprise"
    sequence:
      - action: script.turn_on
        target:
          entity_id: script.nabaztag_dance
      - delay: "00:00:05"
      - action: rest_command.nabaztag_surprise

  nabaztag_bitcoin_info:
    alias: "bitcoin value"
    sequence:
      - condition: state
        entity_id: input_boolean.nabaztaglife
        state: "on"
      - action: rest_command.nabaztag_say
        data:
          message: >
            Bonjour !
            Le Bitcoin vaut {{ states('sensor.bitcoin_exchange_rate') }} euros.
